# docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:stable jekyll serve

version: '3'
services: 
    jekyll-serve:
        image: jekyll/jekyll:add_jasper2-pages
        volumes:
            - '.:/srv/jekyll'
        ports:
            - 4000:4000
        command: 'jekyll serve --force_polling --incremental'
        # command: 'jekyll serve --force_polling'
